def cateye():

    import tkinter as tk
    t=tk.Tk()
    #t.geometry('1225x700')
    t.title('pixel art')
    t['bg']='black'

    # Create a canvas to hold the pixel art grid
    canvas = tk.Canvas(t, width=790, height=500)
    canvas.pack()

    # Create a vertical scrollbar
    scrollbar = tk.Scrollbar(t, orient="vertical", command=canvas.yview)
    scrollbar.pack(side="right", fill="y")

    # Configure the canvas to work with the scrollbar
    canvas.configure(yscrollcommand=scrollbar.set)

    # Create a frame to contain your pixel art grid
    frame = tk.Frame(canvas)
    canvas.create_window((0, 0), window=frame, anchor="nw")

    l1=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=1,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=1,column=105)
    ################################################################

    l1=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=2,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=2,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=2,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=2,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=2,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=2,column=105)
    ###############################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=3,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=3,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=3,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=3,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=3,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=3,column=105)
    ########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=4,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=4,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=4,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=4,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=4,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=4,column=105)
    #########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=5,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=5,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=5,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=5,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='white').grid(row=5,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='white').grid(row=5,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=5,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=5,column=105)
    ############################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=6,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=6,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=6,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=6,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='white').grid(row=6,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='white').grid(row=6,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='black').grid(row=6,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=6,column=105)
    ###############################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=7,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=7,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=7,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='white').grid(row=7,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='white').grid(row=7,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=7,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='black').grid(row=7,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=7,column=105)
    ####################################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=8,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=8,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=8,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=8,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='black').grid(row=8,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=8,column=105)
    #############################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=9,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=9,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=9,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=9,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=9,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=9,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=9,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=9,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=9,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=9,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='black').grid(row=9,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=9,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=9,column=105)
    ##########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=10,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=10,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=10,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lawngreen').grid(row=10,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=10,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=10,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=10,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=10,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=10,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='black').grid(row=10,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=10,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=10,column=105)
    #########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=11,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=11,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=11,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=11,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=11,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=11,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=11,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=11,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=11,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=11,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=11,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=11,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=11,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=11,column=105)
    ###########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=12,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=12,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=12,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=12,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=12,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=12,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=12,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=12,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=12,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=12,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=12,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=12,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=12,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=12,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=12,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=12,column=105)
    #######################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='black').grid(row=13,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='black').grid(row=13,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=13,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=13,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='lawn green').grid(row=13,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=13,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=13,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=13,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=13,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=13,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=13,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=13,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=13,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=13,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=13,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='orange').grid(row=13,column=105)
    ####################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=14,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='yellow').grid(row=14,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=14,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=14,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=14,column=105)
    #########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=15,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=15,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=15,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='green yellow').grid(row=15,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='lime green').grid(row=15,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=15,column=105)
    ###############################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=16,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=16,column=105)
    #########################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=17,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='black').grid(row=17,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='black').grid(row=17,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=17,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=17,column=105)
    ##################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=18,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='black').grid(row=18,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=18,column=105)
    #######################################################################

    l1=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=5)
    l2=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=10)
    l3=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=15)
    l4=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=20)
    l5=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=25)
    l6=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=30)
    l7=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=35)
    l8=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=40)
    l9=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=45)
    l10=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=50)
    l11=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=55)
    l12=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=60)
    l13=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=65)
    l14=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=70)
    l15=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=75)
    l16=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=80)
    l17=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=85)
    l18=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=90)
    l19=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=95)
    l20=tk.Button(frame,width=4,height=2,bg='orange').grid(row=19,column=100)
    l21=tk.Button(frame,width=4,height=2,bg='black').grid(row=19,column=105)

    l1 = tk.Label(t,text="Cat Eye", foreground='white')
    l1.config(font=("times",20,'bold'),width=20, height=2,bg="black")
    l1.pack()

    l2 = tk.Label(t,text="Size: 19 x 21 (row x column)", foreground='white')
    l2.config(font=("times",20,'bold'),width=40, height=1,bg="black")
    l2.pack()

    l3 = tk.Label(t,text="Colours Used: Orange, Black, Lime Green, Green Yellow, Lawn Green", foreground='white')
    l3.config(font=("times",20,'bold'),width=100, height=1,bg="black")
    l3.pack()

    l4 = tk.Label(t,text="For Crochet Users: 1 Pixel=2 Double Crochet", foreground='white')
    l4.config(font=("times",20,'bold'),width=70, height=1,bg="black")
    l4.pack()

    # Update the canvas scroll region
    frame.update_idletasks()
    canvas.config(scrollregion=canvas.bbox("all"))
