def nightcat():
    import tkinter as tk
    t=tk.Tk()
    #t.geometry('2000x1000')
    t.title('night cat')
    t['bg']='black'

    # Create a canvas to hold the pixel art grid
    canvas = tk.Canvas(t, width=990, height=500,)
    canvas.pack()

    # Create a vertical scrollbar
    scrollbar = tk.Scrollbar(t, orient="vertical", command=canvas.yview)
    scrollbar.pack(side="right", fill="y")

    # Configure the canvas to work with the scrollbar
    canvas.configure(yscrollcommand=scrollbar.set)

    # Create a frame to contain your pixel art grid
    frame = tk.Frame(canvas)
    canvas.create_window((0, 0), window=frame, anchor="nw")


    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=1,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=1,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=1,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=1,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=1,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=1,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=1,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=1,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=1,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='white').grid(row=1,column=160)
    #####################################################################

    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=2,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=2,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=2,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=2,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=2,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=2,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=2,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=2,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=2,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=2,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=2,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='white').grid(row=2,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='white').grid(row=2,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='white').grid(row=2,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='white').grid(row=2,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='white').grid(row=2,column=160)
    ################################################################

    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=3,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=3,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=3,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=3,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=3,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=3,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=3,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=3,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=3,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=3,column=160)
    ##################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=4,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=4,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=4,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=4,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=4,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=4,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=4,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=4,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=4,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=4,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=4,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=4,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=4,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=4,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=4,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=4,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=4,column=160)
    ########################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=5,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=5,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=5,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=5,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=5,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=5,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=5,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=5,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=5,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=5,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=5,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=5,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=5,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=5,column=160)
    ##############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=6,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=6,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=6,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=6,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=6,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=6,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=6,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=6,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=6,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=6,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=6,column=160)
    ######################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=7,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=7,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=7,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=7,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=7,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=7,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=7,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=7,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=7,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=7,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='cornflower blue').grid(row=7,column=160)
    ############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=8,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=8,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=8,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=8,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=8,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=8,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royal blue').grid(row=8,column=160)
    #######################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=9,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=9,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=9,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=9,column=160)
    ########################################################################3

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=10,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=10,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=10,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=10,column=160)
    ################################################################3

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=11,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=11,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=11,column=160)
    #########################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=12,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=12,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=12,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=12,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=12,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=12,column=160)
    ######################################################################

    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=13,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=13,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=13,column=160)
    ########################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=14,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=14,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=14,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=14,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=14,column=160)
    #################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=15,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=15,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=15,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=15,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=15,column=160)
    ###########################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=16,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=16,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=16,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=16,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=16,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=16,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=16,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=16,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=16,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=16,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='white').grid(row=16,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='white').grid(row=16,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=16,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=16,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=16,column=160)
    ##############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=17,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=17,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=17,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=17,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=17,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=17,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=17,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=17,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=17,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=17,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=17,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=17,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=17,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='white').grid(row=17,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='white').grid(row=17,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='white').grid(row=17,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=17,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=17,column=160)
    ##############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=18,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=18,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=18,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=18,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=18,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='steel blue1').grid(row=18,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='steel blue1').grid(row=18,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=18,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=18,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=18,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=18,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=18,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=18,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=18,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=18,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=18,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='white').grid(row=18,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='white').grid(row=18,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='white').grid(row=18,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=18,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=18,column=160)
    ##############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=19,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=19,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=19,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=19,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=19,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=19,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=19,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=19,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='white').grid(row=19,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='white').grid(row=19,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=19,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=19,column=160)
    ##############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=20,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=20,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=20,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=20,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=20,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=20,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=20,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=20,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=20,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=20,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=20,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=20,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=20,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='white').grid(row=20,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='white').grid(row=20,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=20,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=20,column=160)
    ##############################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=21,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=21,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='steel blue1').grid(row=21,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=21,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=21,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=21,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=21,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=21,column=160)
    ##################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=22,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='navy').grid(row=22,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=22,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=22,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=22,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=22,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=22,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=22,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=22,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=22,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='navy').grid(row=22,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=22,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=22,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=22,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=22,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=22,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=22,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=22,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=22,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=22,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=22,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=22,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=22,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=22,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=22,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=22,column=160)
    ###############################################################################

    l1=tk.Button(frame,width=3,height=1,bg='slateblue4').grid(row=23,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='navy').grid(row=23,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=23,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=23,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='navy').grid(row=23,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=23,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=23,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=23,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=23,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=23,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=23,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=23,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=23,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=23,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='lightblue1').grid(row=23,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=23,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=23,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=23,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=23,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=23,column=160)
    ##################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=24,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=24,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=24,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=24,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=24,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=24,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=24,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=24,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=24,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=24,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=24,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=24,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=24,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=24,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=24,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=24,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=24,column=160)
    ###################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=25,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=25,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='skyblue3').grid(row=25,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=25,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=25,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=25,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=25,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=25,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=25,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=25,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=25,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=25,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=25,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='sky blue').grid(row=25,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='navy').grid(row=25,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=25,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=25,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=25,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=25,column=160)
    ################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=26,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=26,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=26,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=26,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=26,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=26,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue2').grid(row=26,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=26,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=26,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='sky blue1').grid(row=26,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=26,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=26,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=26,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=26,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=26,column=160)
    ####################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=27,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=27,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=27,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=27,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='skyblue1').grid(row=27,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=27,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=27,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=27,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=27,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=27,column=160)
    ####################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=28,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=28,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=28,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='sky blue3').grid(row=28,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=28,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=28,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=28,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=28,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=28,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=28,column=160)
    ####################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=29,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=29,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='midnight blue').grid(row=29,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=29,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=29,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=29,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=29,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=29,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=29,column=160)
    ############################################################################
    
    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=30,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=30,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue4').grid(row=30,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=30,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=30,column=160)
    #########################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='royalblue3').grid(row=31,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=31,column=160)
    ################################################################################

    l1=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=5)
    l2=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=10)
    l3=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=15)
    l4=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=20)
    l5=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=25)
    l6=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=30)
    l7=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=35)
    l8=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=40)
    l9=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=45)
    l10=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=50)
    l11=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=55)
    l12=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=60)
    l13=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=65)
    l14=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=70)
    l15=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=75)
    l16=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=80)
    l17=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=85)
    l18=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=90)
    l19=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=95)
    l20=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=100)
    l21=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=105)
    l22=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=110)
    l23=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=115)
    l24=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=120)
    l25=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=125)
    l26=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=130)
    l27=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=135)
    l28=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=140)
    l29=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=145)
    l30=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=150)
    l31=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=155)
    l32=tk.Button(frame,width=3,height=1,bg='deepskyblue2').grid(row=32,column=160)

    l1 = tk.Label(t,text="Night Sky Cat", foreground='white')
    l1.config(font=("times",20,'bold'),width=20, height=2,bg="black")
    l1.pack()

    l2 = tk.Label(t,text="Size: 32 x 32 (row x column)", foreground='white')
    l2.config(font=("times",20,'bold'),width=40, height=1,bg="black")
    l2.pack()

    l3 = tk.Label(t,text="Colours Used: MidnightBlue,SlateBlue,SkyBlue,DeepSkyBlue,CornflowerBlue,Navy,LightBlue,RoyalBlue,White", foreground='white')
    l3.config(font=("times",20,'bold'),width=100, height=1,bg="black")
    l3.pack()

    l4 = tk.Label(t,text="For Crochet Users: 1 Pixel=2 Double Crochet", foreground='white')
    l4.config(font=("times",20,'bold'),width=70, height=1,bg="black")
    l4.pack()

    # Update the canvas scroll region
    frame.update_idletasks()
    canvas.config(scrollregion=canvas.bbox("all"))

    t.mainloop()
